# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Values.pv.name}}
spec:
  storageClassName: ""
  capacity:
    storage: {{.Values.pv.storage}}
  accessModes:
    - {{.Values.pv.mode}}
  hostPath:
    path: "{{.Values.pv.path}}"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.pvc.name}}
spec:
  accessModes:
    - {{.Values.pv.mode}}
  resources:
    requests:
      storage: {{.Values.pv.storage}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Values.databaseConfig.name}}"
  labels:
    name: "{{.Values.databaseConfig.name}}"
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "{{.Values.databaseConfig.name}}"
  template:
    metadata:
      labels:
        name: "{{.Values.databaseConfig.name}}"
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - image: "{{.Values.databaseConfig.repository}}/{{.Values.databaseConfig.container}}:{{.Values.databaseConfig.tag}}"
        name: {{.Values.databaseConfig.name}}
        env:
        - name: POSTGRES_DB
          value: "{{.Values.databaseEnvironment.pgDatabase}}"
        - name: POSTGRES_USER
          value: "{{.Values.databaseEnvironment.pgUser}}"
        - name: POSTGRES_PASSWORD
          value: "{{.Values.databaseEnvironment.pgPassword}}"
        - name: PGDATA
          value: "{{.Values.pv.path}}/pgdata"
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - "{{.Values.databaseEnvironment.pgUser}}"
            - -d
            - "{{.Values.databaseEnvironment.pgDatabase}}"
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - "{{.Values.databaseEnvironment.pgUser}}"
            - -d
            - "{{.Values.databaseEnvironment.pgDatabase}}"
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
          - mountPath: {{.Values.pv.path}}
            name: {{.Values.pv.name}}
        ports:
          - containerPort: {{.Values.databaseConfig.port }}
            protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.databaseConfig.cpu }}
            memory: {{ .Values.databaseConfig.memory }}
      volumes:
        - name: {{.Values.pv.name}}
          persistentVolumeClaim:
            claimName: {{.Values.pvc.name}}
            readOnly: false
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.databaseConfig.name}}"
  labels:
    name: "{{.Values.databaseConfig.name}}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  type: "{{.Values.databaseConfig.serviceType}}"
  ports:
  - protocol: TCP
    port: {{.Values.databaseConfig.port}}
    targetPort: {{.Values.databaseConfig.port}}
    name: "{{.Values.databaseConfig.name}}"
  selector:
    name: "{{.Values.databaseConfig.name}}"
