# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.syncopeConsoleConfig.name}}
spec:
  replicas: {{ .Values.syncopeConsoleConfig.replicas }}
  selector:
    matchLabels:
      name: {{.Values.syncopeConsoleConfig.name}}
  template:
    metadata:
      labels:
        name: {{.Values.syncopeConsoleConfig.name}}
    spec:
      containers:
      - name: {{.Values.syncopeConsoleConfig.name}}
        envFrom:
        - configMapRef:
           name: syncope-environment-config
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: SERVER_FORWARD_HEADERS_STRATEGY
          value: framework
        - name: CONSOLE_X_FORWARD_HTTP_PORT
          value: {{ dig "consoleLocalPort" 28080 .Values.ingress | toString | quote }}
        - name: JAVA_TOOL_OPTIONS
          value: "-Dconsole.xForwardHttpPort={{ dig "consoleLocalPort" 28080 .Values.ingress }}"
        - name: KEYMASTER_ADDRESS
          value: http://{{ .Values.syncopeConfig.name }}:8080/syncope/rest/keymaster
        - name: SERVICE_DISCOVERY_ADDRESS
          value: http://{{ .Values.syncopeConsoleConfig.name }}:8080/syncope-console/
        image: "{{.Values.syncopeConsoleConfig.repository}}/{{.Values.syncopeConsoleConfig.container}}:{{.Values.syncopeConsoleConfig.tag}}"
        imagePullPolicy: {{ .Values.syncopeConsoleConfig.imagePullPolicy | default "IfNotPresent" }}
        ports:
        - containerPort: {{.Values.syncopeConsoleConfig.containerPort}}
        resources:
          requests:
            memory: {{ .Values.syncopeConsoleConfig.memoryLimit }}
          limits:
            memory: {{ .Values.syncopeConsoleConfig.memoryLimit }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.syncopeConsoleConfig.name}}"
spec:
  type: "{{.Values.syncopeConsoleConfig.serviceType}}"
  selector:
    name: "{{.Values.syncopeConsoleConfig.name}}"
  ports:
  - port: {{.Values.syncopeConsoleConfig.containerPort}}
    targetPort: {{.Values.syncopeConsoleConfig.containerPort}}
    name: http-api
